version: "3.9"
services:

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=library
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes: 
      - ./db-data:/var/lib/postgresql/data
      - ./create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql

  app:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "9090:9090"